### ISSUE TITLE
createReadStream / readFileSync

### ISSUE THREAD

**Issue by danshirley1** [miguelmota/http-message-parser#1]
Hi Miguel, we're really grateful for the module it's helping us enormously!

One thing I noticed this morning is that in your example:
https://github.com/miguelmota/http-message-parser

You use 'createReadStream':
const parsedMessage = httpMessageParser(fs.createReadStream('multipart_example.txt'));

This always returns null values in the parsed result.

I noticed in your test case:
https://github.com/miguelmota/http-message-parser/blob/master/test/http-message-parser.js

That you are using 'readFileSync':
const data = fs.readFileSync(`${__dirname}/data/test_1/message.txt`);

This works - just wanted to point out that either the example docs need updating or, well it's up to you.

Thanks

**Comment by miguelmota** [comment]
@cowboyfromhull shoot, you're right, it's wrong in the README. httpMessageParser takes in a string or Buffer only. 

The README is now updated with:

``` javascript
const httpMessageParser = require('http-message-parser');
const fs = require('fs');

fs.readFile('multipart_example.txt', 'binary', (error, messageBuffer) => {
  if (error) {
    return console.error(error);
  }

  const parsedMessage = httpMessageParser(messageBuffer);

  console.log(parsedMessage);
});
```

**Comment by miguelmota** [comment]
@cowboyfromhull do you think it would be a good idea to be able to pass in a Stream and return a readable stream?

**Comment by danshirley1** [comment]
Without looking at the benefits of each in more detail I can't say, it's working now for our immediate needs so cheers!

**Comment by miguelmota** [comment]
@cowboyfromhull good to know :) I'll leave this issue open in case other people run into similar situations
