### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by shsander** [miguelmota/http-message-parser#3]
I was using this module to parse multipart responses from a microservice, and it was taking way too much CPU (especially for large responses). I tracked the problem down to the following code:

```
for (var j = 0; j < message.length; j++) {
      var boundaryMatch = message.slice(j, j + fullBoundary.length).toString();

      if (boundaryMatch === fullBoundary) {
               boundaryIndexes.push(j);
      }
}
```

The following seems to be equivalent, but much more efficient:

```
for (var j = 0; j >= 0;) {
      j = message.indexOf(fullBoundary, j);

      if (j >= 0) {
          boundaryIndexes.push(j);
           j += fullBoundary.length;
      }
}
```

**Comment by miguelmota** [comment]
@shsander implemented your change, thanks for reporting!
