### ISSUE TITLE
Publish as ES5 to npm

### ISSUE THREAD

**Issue by s-maheshbabu** [miguelmota/http-message-parser#5]
http-messsage-parser isn't working with some tools (create-react-app) and some 'non-latest' browsers. 

The general guidance based on my research appears to be to release to npm as ES5 for a few years. 

For example, [here is a snippet](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) from Facebook recommending that packages be published pre-compiled.

Is that something that can be done for this package?

**Comment by miguelmota** [comment]
@s-maheshbabu the latest release now has only ES5 syntax. Reopen issue if it's not working for you still.

Thanks for reporting!

**Comment by s-maheshbabu** [comment]
That worked. Thanks for fixing the issue.

**Comment by miguelmota** [comment]
No problem!
